version: 2.1

jobs:
  bazel-build-all:
    docker:
      - image: docker.io/envoyproxy/envoy-build@sha256:afe3addcdb7a5177bcca77d041f079acf4a6c5fb32701aadb2ab96fd0933e0b2
    steps:
      - checkout
      - run:
          name: Bazel environment
          command: |
            bazel --version
            bazel info release
      - run:
          name: Build as much as possible with Bazel
          no_output_timeout: 30m
          command: |
            # Keep going so we can capture as many build results as possible.
            bazel build \
              --config=clang \
              --config=ci \
              --keep_going \
              //... \
              -//api/... \
              -//docs/... \
              -//mobile/...

workflows:
  bazel:
    jobs:
      - bazel-build-all
